apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: snechar/accountmicroservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: account-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: account
  ports:
   - name: account-srv
     protocol: TCP
     port: 80
     targetPort: 80
   - name: accountgrpc
     protocol: TCP
     port: 666
     targetPort: 666


