apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-depl
spec:
  #replicas: 3
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: snechar/accountmicroservice:latest
          resources:
          # You need to specify the metric the HPA object will reference
          # kubectl -n kubernetes-dashboard get secret $(kubectl -n kubernetes-dashboard get sa/admin-user -o jsonpath="{.secrets[0].name}") -o go-template="{{.data.token | base64decode}}"
          #kubectl -n kubernetes-dashboard create token admin-user
           limits:
             cpu: 200m
             memory: 500Mi
           requests:
             cpu: 100m
             memory: 200Mi
          

---
apiVersion: v1
kind: Service
metadata:
  name: account-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: account
  ports:
   - name: account-srv
     protocol: TCP
     port: 80
     targetPort: 80
   - name: accountgrpc
     protocol: TCP
     port: 666
     targetPort: 666


