apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: watchtime.com
      http:
        paths:
          - path: /api/authenticate/login
            pathType: Prefix
            backend:
              service:
                name: account-clusterip-srv
                port:
                  number: 80
          - path: /eventbus
            pathType: Prefix
            backend:
              service:
                name: nats-clusterip-srv
                port:
                  number: 4222
          

