apiVersion: apps/v1
kind: Deployment
metadata:
  name: videoservice-depl
spec:
  #replicas: 3
  selector:
    matchLabels:
      app: videoservice
  template:
    metadata:
      labels:
        app: videoservice
    spec:
      containers:
        - name: videoservice
          image: snechar/videoservice:latest
          volumeMounts:
            - name: local-persistent-storage
              mountPath: /mnt
          volumes:
            - name: local-persistent-storage
              persistentVolumeClaim:
                 claimName: test-pvc
          resources:
          # You need to specify the metric the HPA object will reference
          # kubectl -n kubernetes-dashboard get secret $(kubectl -n kubernetes-dashboard get sa/admin-user -o jsonpath="{.secrets[0].name}") -o go-template="{{.data.token | base64decode}}"
           limits:
             cpu: 200m
             memory: 500Mi
           requests:
             cpu: 100m
             memory: 200Mi

---
apiVersion: v1
kind: Service
metadata:
  name: videoservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: videoservice
  ports:
   - name: videoservice-srv
     protocol: TCP
     port: 80
     targetPort: 80
   - name: videoservicegrpc
     protocol: TCP
     port: 666
     targetPort: 666


